### ISSUE TITLE
Looks like an invalid image, trying a different reader for...

### ISSUE THREAD

**Issue by rannaot** [YAMJ/yamj-v2#2792]
I keep getting this message, no images are being download..:

"Searching for information on the video files...
MediaInfo tool will be used to extract video data. But not RAR and ISO formats
Processing new video: Alfred Hitchcock - North By Northwest
Looks like an invalid image, trying a different reader for URL: http://image.tmd
b.org/t/p/original/oCrZCT5MLzo8j231IdsOXhGsGpX.jpg
Looks like an invalid image, trying a different reader for URL: <head><meta http...."

Any idea?

**Comment by Omertron** [comment]
Yes, java has a rather strict interpretation of the JPEG standard and some images, whilst able to be displayed fine on a web browser, cause it problems (such as this).

There are two work arounds. Firstly, try downloading the image, open it in an image program (GiMP for example) and resize it by 1 pixel and save it. This image should then work with YAMJ but will need to be saved with the video files it's associated with.

Alternatively, you can specify a URL to a different image in the NFO file.

**Comment by Riquito62** [comment]
Hi,

i've exactly the same problem with downloading from Thetvdb.com ... all my posters since last week.
May be a new update of Windows 10 ?
I've changed Nothing from my prperties files or Cmd 

here is the messages : 
_Checking existing video: Boardwalk Empire [Season 3]
allocine is not a TvShow Poster plugin - skipping
Finished: Body Of Proof [Season 1] (135/1330)
Checking existing video: Body Of Proof [Season 3]
Looks like an invalid image, trying a different reader for URL: http://thetvdb.com/banners/seasons/167591-3-2.jpg
allocine is not a TvShow Poster plugin - skipping
Finished: Body Of Proof [Season 2] (136/1330)
Checking existing video: Bomb Girls [Season 1]
Looks like an invalid image, trying a different reader for URL: http://thetvdb.com/banners/seasons/254378-1-3.jpg
allocine is not a TvShow Poster plugin - skipping
Finished: Body Of Proof [Season 3] (137/1330)
Checking existing video: Bonekickers [Season 1]
Looks like an invalid image, trying a different reader for URL: http://thetvdb.com/banners/seasons/82456-1.jpg
allocine is not a TvShow Poster plugin - skipping
...

**Comment by Omertron** [comment]
Seems that something has changed with the way the images are served from TheTVDB.

I think the http redirect is causing issues with the dimension reader. So the simplest solution is to turn of the URL aspect validation with the following setting
````
poster.scanner.Validate=false
````
