### ISSUE TITLE
TV jpg not downloading.

### ISSUE THREAD

**Issue by Robo2017** [YAMJ/yamj-v2#2799]
Hi

Over the past few weeks/month or so I have had a strange issue where the images for new TV series have stopped downloading and are being replaced by the dummy image.
All other images including fanart and videoimage are downloading fine as is any image for a film.

I have tried updating Yanj and Java but the problem still remains - any one else having this issue or know how to resolve.

I have checked the log file and for every new TV show no poster is found? example of output below.

PosterScanner: Checking for 'Season 6.*' posters
PosterScanner: No local poster found for

Any advise / help would greatly be appreciated.

**Comment by Verakso** [comment]
I can tell you that is most likely the same as this error #2797 
I some other threads I saw some mentions about a possible issue that it could have been caused in the new Java stack, but I have tried to run YAMJ with an elder Java stack, and the issue is still there.

The only current workaround I know is to manually download the images you self.

**Comment by Robo2017** [comment]
Indeed it does seem to be the same - I will downloaded manually as suggested and wait hopefully for a fix.
Thanks.

**Comment by Omertron** [comment]
See #2796

**Comment by Robo2017** [comment]
Thanks - I'll give it a go
